######### NORMAL OPERATION  ###########

### Login the defaults admins
POST https://ipl-web2-projet-backend.herokuapp.com/auths/login
Content-Type: application/json

{
    "email":"estelle.croquet@student.vinci.be",
    "password":"admin"
}


#signup(username, userlastname, password, email, address)
### Signup a new user
POST http://localhost:3000/auths/signup
Content-Type: application/json

{
    "username": "Chaymae", 
    "userlastname": "Hbat",
    "password":"admin",     
    "email":"chaymae.hbat@student.vinci.be",
    "address":"zza"
}

